weaviate/docs

- secondaryNavbar.js
Rename `Build` to `Weaviate`
> note, you can run `yarn verify-links` to test site links locally
> Rename `Build` to `Weaviate`

- netlify.toml
> add netlify redirects

- docs/integrations/recipes/agent-workflow-with-weaviate-query-agent.md
> Fix broken link

- secondaryNavbar.js
> Fix recipes navigation

- _includes/code/python/local.quickstart.import_objects.py
- _includes/code/python/quickstart.import_objects.py
> [Improvement] Remove dynamic batch import

- _build_scripts/link-validator.js
Add GitHub link validation ignore because of Too Many Requests 429 errors.
> Add GitHub link validation ignore

- docs/deploy/config-guides/monitoring.md
> updating monitoring doc with additional metrics

- docs/deploy/config-guides/tenant-offloading.md
- docs/weaviate/configuration/modules.md
- docs/weaviate/modules/index.md
- docs/weaviate/starter-guides/managing-resources/index.md
- docs/weaviate/starter-guides/managing-resources/tenant-states.mdx
- sidebars.js
- site.redirects.js
> added tenant offloading and updated redirects

- docs/deploy/installation-guides/aws-marketplace.md
- docs/deploy/installation-guides/ecs-marketplace.md
- docs/deploy/installation-guides/eks-marketplace.md
- sidebars.js
> adding new marketplace doc and updated sidebar

- docs/deploy/installation-guides/aws-marketplace.md
- docs/deploy/installation-guides/eks.md
> added guideflows to AWS marketplace installation pages

- netlify.toml
> [Improvement] Add redirects

- netlify.toml
> [Production] Fix ahrefs redirects

- docs/cloud/manage-clusters/upgrade.mdx
Fix list styling in Cloud cluster update guide.
> [Fix] Update list

- _includes/code/python/howto.configure.rbac.roles.py
- _includes/code/python/howto.configure.replica.movement.py
- docs/deploy/configuration/env-vars/index.md
- docs/deploy/configuration/replica-movement.mdx
- docs/deploy/configuration/replication.md
- docs/weaviate/concepts/replication-architecture/cluster-architecture.md
- docs/weaviate/concepts/replication-architecture/consistency.md
- docs/weaviate/configuration/rbac/index.mdx
- docs/weaviate/configuration/rbac/manage-roles.mdx
- sidebars.js
- tests/docker-compose-anon-2.yml
- tests/docker-compose-anon-bind.yml
- tests/docker-compose-anon-clip.yml
- tests/docker-compose-anon-offload.yml
- tests/docker-compose-anon.yml
- tests/docker-compose-rbac.yml
- tests/docker-compose-three-nodes.yml
- tests/docker-compose.yml
Add docs for the upcoming replica movement feature.
> [v1.32] Replica movement docs

- docs/deploy/installation-guides/gcp-marketplace.md
- docs/deploy/installation-guides/gke-marketplace.md
> added GCP guideflows

- .vscode/settings.json
- _includes/code/howto/java/pom.xml
- _includes/code/howto/java/src/test/java/io/weaviate/docs/backups.java
- _includes/code/howto/java/src/test/java/io/weaviate/docs/manage-data.collection-aliases.java
- _includes/code/howto/java/src/test/java/io/weaviate/docs/manage-data.replica-movement.java
- _includes/code/howto/java/src/test/java/io/weaviate/docs/quickstart_local/RAG.java
- _includes/code/howto/java/src/test/java/io/weaviate/docs/rq-compression.java
- _includes/code/howto/java/src/test/java/io/weaviate/docs/sq-compression.java
- docs/weaviate/configuration/compression/rq-compression.md
- docs/weaviate/configuration/compression/sq-compression.md
- docs/weaviate/manage-collections/collection-aliases.mdx
- docs/weaviate/starter-guides/managing-collections/index.mdx
Java code snippets for:
- replicate movement
- collection aliases
- RQ
- restoring roles and users
Additional:
- added SQ for Java
- refactored backups code
> [New docs] Java code for v1.32

- _includes/code/howto/configure-rq/rq-compression-v4.py
- _includes/code/howto/configure-sq/sq-compression-v4.py
- _includes/code/howto/configure.bq-compression.py
- _includes/code/howto/configure.pq-compression.py
- tests/test_compression.py
Add properties to collections for testing quantization.
> [Fix] Quantization examples without properties

- _includes/1-25-replication-factor.mdx
- docs/deploy/configuration/replica-movement.mdx
> updated the replica movement page and replication factor admonition

- docs/integrations/cloud-hyperscalers/google/index.md
- docs/weaviate/model-providers/_includes/google-api-key-note.md
- docs/weaviate/model-providers/google/embeddings-multimodal.md
- docs/weaviate/model-providers/google/embeddings.md
- docs/weaviate/model-providers/google/generative.md
- docs/weaviate/model-providers/google/index.md
- docs/weaviate/model-providers/index.md
- sidebars.js
20250811 Google model updates
- Update model names
- AI studio -> Gemini API
> 20250811 Google model updates

- _includes/code/config-refs/reference.collections.py
- docs/weaviate/concepts/indexing/inverted-index.md
- docs/weaviate/config-refs/indexing/inverted-index.mdx
Add further clarification on how tokenization impacts inverted index creation and link to the appropriate reference section.
> [Improvement] Tokenization clarification

- _includes/code/python/best-practices.python.ai.py
- docs/weaviate/best-practices/code-generation.md
- sidebars.js
- Update vibe coding guide
- Move the guide to root level
> 20250817 Update vibe coding guide

- _includes/code/howto/manage-data.collections.py
- _includes/code/howto/manage-data.collections.ts
- docs/weaviate/manage-collections/collection-operations.mdx
Add docs re checking if a collection exists
> Add docs re checking if a collection exists 

- _includes/code/howto/manage-data.collections.py
> [Testing] Fix Python test

- _includes/code/python/best-practices.python.ai.py
> Update generative explanation

- _includes/code/howto/manage-data.import.py
- docs/weaviate/concepts/data-import.mdx
- docs/weaviate/manage-objects/import.mdx
- tests/docker-compose-anon.yml
Adding docs for using server-side batch imports and a conceptspage explaining the different import techniques.
> [v1.33] Server-side batch imports

- docs/deploy/installation-guides/k8s-installation.md
> updated K8s doc with info on internode auth

- _includes/code/howto/go/docs/configure/rbac.oidc.users_test.go
- _includes/code/howto/go/docs/configure/rbac.roles_test.go
- _includes/code/howto/go/docs/configure/rbac.users_test.go
- docs/weaviate/configuration/rbac/manage-roles.mdx
- docs/weaviate/configuration/rbac/manage-users.mdx
> Add Go snippets

- _includes/code/howto/go/docs/configure/rbac.oidc.users_test.go
- _includes/code/howto/go/docs/configure/rbac.roles_test.go
- _includes/code/howto/go/docs/configure/rbac.users_test.go
- _includes/code/howto/java/src/test/java/io/weaviate/docs/rbac-oidc-users.java
- _includes/code/howto/java/src/test/java/io/weaviate/docs/rbac-roles.java
- _includes/code/howto/java/src/test/java/io/weaviate/docs/rbac-users.java
- docs/weaviate/configuration/rbac/manage-roles.mdx
- docs/weaviate/configuration/rbac/manage-users.mdx
Add Java & Go RBAC code snippets.
> Java & Go RBAC
